name: CI
on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-22.04
        env:
            php-version: "8.1"
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: ${{ env.php-version }}
                  tools: cs2pr, php-cs-fixer:3.13
                  coverage: none

            - name: "Run PHP-CS-Fixer"
              run: php-cs-fixer fix -v --dry-run --format=checkstyle | cs2pr

    phpstan:
        name: "PHPStan"
        runs-on: ubuntu-20.04
        env:
            php-version: "8.1"
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.php-version }}
                  coverage: none

            - name: "Install Dependencies with Composer"
              uses: "ramsey/composer-install@v2"

            - name: "Run PHPStan"
              run: vendor/bin/phpstan analyse --error-format=github

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-20.04
        env:
            php-version: "8.1"
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.php-version }}
                  coverage: pcov

            - name: "Install Dependencies with Composer"
              uses: "ramsey/composer-install@v2"

            - name: "Setup Problem Matchers for PHPUnit"
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Run PHPUnit"
              run: vendor/bin/phpunit --coverage-text
